# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: error_handling_example.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'error_handling_example.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1c\x65rror_handling_example.proto\x12\x16\x65rror_handling_example\"2\n\rDivideRequest\x12\x10\n\x08\x64ividend\x18\x01 \x01(\x01\x12\x0f\n\x07\x64ivisor\x18\x02 \x01(\x01\"\"\n\x0e\x44ivideResponse\x12\x10\n\x08quotient\x18\x01 \x01(\x01\x32\x65\n\nCalculator\x12W\n\x06\x44ivide\x12%.error_handling_example.DivideRequest\x1a&.error_handling_example.DivideResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'error_handling_example_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_DIVIDEREQUEST']._serialized_start=56
  _globals['_DIVIDEREQUEST']._serialized_end=106
  _globals['_DIVIDERESPONSE']._serialized_start=108
  _globals['_DIVIDERESPONSE']._serialized_end=142
  _globals['_CALCULATOR']._serialized_start=144
  _globals['_CALCULATOR']._serialized_end=245
# @@protoc_insertion_point(module_scope)
