# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: example.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'example.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rexample.proto\"!\n\x0e\x45xampleRequest\x12\x0f\n\x07message\x18\x01 \x01(\t\"\"\n\x0f\x45xampleResponse\x12\x0f\n\x07message\x18\x01 \x01(\t2B\n\x0e\x45xampleService\x12\x30\n\tUnaryCall\x12\x0f.ExampleRequest\x1a\x10.ExampleResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'example_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EXAMPLEREQUEST']._serialized_start=17
  _globals['_EXAMPLEREQUEST']._serialized_end=50
  _globals['_EXAMPLERESPONSE']._serialized_start=52
  _globals['_EXAMPLERESPONSE']._serialized_end=86
  _globals['_EXAMPLESERVICE']._serialized_start=88
  _globals['_EXAMPLESERVICE']._serialized_end=154
# @@protoc_insertion_point(module_scope)
